<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\docs\DirDissasembly\XMED_Offsets.md" Link="XMED_Offsets.md" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../BlingoEngine.IO.Data/BlingoEngine.IO.Data.csproj" />
  </ItemGroup>
</Project>
