<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Platforms>AnyCPU;x64;x86</Platforms>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Setup\**" />
	  <EmbeddedResource Remove="Setup\**" />
	  <None Remove="Setup\**" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\src\BlingoEngine\BlingoEngine.csproj" />
	</ItemGroup>

</Project>

